# Patch @react-native-firebase/firestore (import order + operator keyword fix)
system('node ../scripts/patch-rnfb-firestore-imports.js')

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

ENV['RCT_NEW_ARCH_ENABLED'] = '1'
platform :ios, '15.1'
install! 'cocoapods', :deterministic_uuids => false
prepare_react_native_project!

$RNFirebaseAsStaticFramework = true

target 'WhatByteApp' do
  config = use_native_modules!

  use_frameworks! :linkage => :static

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseAppCheckInterop', :modular_headers => true
  pod 'FirebaseAuthInterop', :modular_headers => true
  pod 'FirebaseCoreExtension', :modular_headers => true
  pod 'FirebaseSharedSwift', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    # Apply to entire Pods project (ensures RNFBApp gets settings)
    installer.pods_project.build_configurations.each do |bc|
      bc.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
    end
    installer.pods_project.targets.each do |target|
      if ['RNFBFirestore', 'RNFBAuth', 'RNFBApp'].include?(target.name)
        target.source_build_phase.files.each do |file|
          if file.settings && file.settings['COMPILER_FLAGS']
            flags = file.settings['COMPILER_FLAGS'].split
            flags.reject! { |flag| flag == '-fno-objc-arc' }
            file.settings['COMPILER_FLAGS'] = flags.join(' ')
          end
          next unless file.file_ref&.path&.end_with?('.m', '.mm')
          file.settings ||= {}
          file.settings['COMPILER_FLAGS'] =
            (file.settings['COMPILER_FLAGS'] || '') + ' -x objective-c++'
        end
      end
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.1'
        # Downgrade non-modular-include from error to warning (RNFBApp imports React-Core headers)
        cflags = config.build_settings['OTHER_CFLAGS'] || '$(inherited)'
        cflags = cflags.is_a?(Array) ? cflags.join(' ') : cflags.to_s
        config.build_settings['OTHER_CFLAGS'] = "#{cflags} -Wno-error=non-modular-include-in-framework-module"
        cxxflags = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
        cxxflags = cxxflags.is_a?(Array) ? cxxflags.join(' ') : cxxflags.to_s
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "#{cxxflags} -Wno-error=non-modular-include-in-framework-module"
      end
    end
  end
end
